### ISSUE TITLE
.lookup() renamed to .getType()

### ISSUE THREAD

**Issue by smilee** [pillarjs/send#202] opened 2021-02-25 23:17 UTC
Version 2 of mime is a breaking change to version 1, where `.lookup()` was renamed to `.getType()`

![image](https://user-images.githubusercontent.com/5793796/109232073-004dbc80-780b-11eb-86f6-3dbc433207b4.png)

[Image source](https://www.npmjs.com/package/mime)

**Comment by dougwilson** [comment] 2021-02-25 23:32
Duplicate of #163

**Closed by dougwilson** 2021-02-25 23:32 UTC
Labels: duplicate
