### ISSUE TITLE
Symlink Files

### ISSUE THREAD

**Issue by shawnzernik** [pillarjs/send#190] opened 2020-02-21 06:33 UTC
Express' Connect will not send files that are symbolic links.

index.js - Line 721

fs.stat(path, function onstat (err, stat) {

Should be

fs.lstat(path, function onstat (err, stat) {

**Comment by dougwilson** [comment] 2020-02-21 06:38
Hello,

Testing just now I am able to send a file that is a symlink just fine, as expected. `fs.stat` will return the stat of the file pointed to by the symlink, which is what is desired here, not to stat the symlink itself.

Perhaps you can provide a full reproduction case of the issue you're having so we can reproduce the failure you are experiencing?

**Comment by shawnzernik** [comment] 2020-02-21 14:47
I'll work on a test case that simplifies the scenario.  I'm on Windows - FS has/had some issues on Windows.

**Comment by dougwilson** [comment] 2020-02-21 14:57
I am also on Windows, but didn't have any issue.

**Comment by dougwilson** [comment] 2022-03-24 00:53
Closing due to no follow up.

**Closed by dougwilson** 2022-03-24 00:53 UTC
Labels: awaiting more info
