### ISSUE TITLE
A named anonymous function issue on Safari's strict mode

### ISSUE THREAD

**Issue by ajhsu** [pillarjs/send#80] opened 2015-09-17 05:17 UTC
In strict mode, Safari 8.0.8 on OS X 10.10.5 raises an exception if a named function's name is the same as one of the function's argument names.

For example: at index.js:L242
`SendStream.prototype.error = function error(status, error) {`

will cause an error on Safari ( but not on Chrome and Firefox ):
`SyntaxError: Cannot declare a parameter named 'error' as it shadows the name of a strict mode function.`

Any sugguestion?

**Comment by dougwilson** [comment] 2015-09-17 05:33
Hi! Yes, that is definitely an issue, as this module does not have any support for web browsers, and would never be expected to function in Safari. The problem is that if there were a true strict mode violation, then we would alter it, but it's actually a known bug in Safari's implementation of strict mode. The problem is that if we cannot add a test that fails with this and passes after the change, then we cannot support altering it, as it'll just get altered back again at some point by another maintainer not knowing.

Now, perhaps the suggested course of action is to get this module to function in web browsers like Safari, contribute CI setup to test this module in Safari and other browsers, and bring web browsers to be supported by this module, if you are up to the task :)

**Comment by dougwilson** [comment] 2015-12-12 04:05
Hi @ajhsu , I assume by the last of response over the months you're not up to the task currently. That's OK! I'm going to close the issue, as we just don't have the resources to support web browsers at the moment, but if you ever get the time to donate your time & effort to add the support, just let us know!

**Closed by dougwilson** 2015-12-12 04:05 UTC
