### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mithun-daa** [pillarjs/send#161] opened 2018-06-11 17:50 UTC
I migrated to node 10.x and I see the following error:

```
http-errors deprecated non-first-argument status code; replace with createError(404, ...) at node_modules/serve-static/node_modules/send/index.js:275:31
```

Thought I'd let you guys know. Please ignore this if I am doing something wrong but please enlighten me if otherwise.

**Comment by dougwilson** [comment] 2018-06-11 18:11
I don't think your issue has to do with the Node.js 10.x migration you did, but we can fix it if you can provide more information. Like 275, in the current version, for instance, it just an assignment (https://github.com/pillarjs/send/blob/master/index.js#L275). Can you provide additional information to help us replicate and track down the issue?

1. Version of this module
2. Code we can run that reproduces the issue

Thank you!

**Comment by mithun-daa** [comment] 2018-06-11 18:18
Version: 0.14.2
Location:
```
SendStream.prototype.error = function error (status, error) {
  // emit if listeners instead of responding
  if (listenerCount(this, 'error') !== 0) {
    return this.emit('error', createError(error, status, {
      expose: false
    }))
  }
...
```
The `createError` inside the `emit` is what the error is pointing to.

**Comment by dougwilson** [comment] 2018-06-11 18:21
So it would seem you have an invalid, incompatible version of the http-errors module installed in your node_module directory. Can you paste the output of `npm ls >/dev/null` ?

**Comment by mithun-daa** [comment] 2018-06-11 18:35
```
npm ERR! missing: compression@1.7.2, required by cobaltwp@0.0.0
npm ERR! missing: debug@2.6.9, required by compression@1.7.2
```

FWIW, Send is a dependency of a dependency. Not sure if `npm ls >/dev/null` would bubble that up.

**Comment by dougwilson** [comment] 2018-06-11 18:38
Gotcha. But yea, either (a) your install tree is corrupted and you have an incompatible version of http-errors installed or (b) it was a bug in the older send since fixed. Can you at least try to use the current version of send to see if you still have the issue? If it's a bug we have to fix you'd have to upgrade regardless so may as well confirm the issue still exists in the current version or not as the first step.

**Comment by mithun-daa** [comment] 2018-06-11 18:57
Will check my versions and let you know if I find anything.

**Comment by dougwilson** [comment] 2018-07-07 21:38
Closing due to no further response. I hope you were able to figure it out!

**Closed by dougwilson** 2018-07-07 21:38 UTC
Labels: awaiting more info
