### ISSUE TITLE
mime.lookup is not a function

### ISSUE THREAD

**Issue by ohhyunjin** [pillarjs/send#203] opened 2021-04-09 17:59 UTC
I keep getting this error when running my react app, as far as I know it's happening because the mime library released a new version with breaking changes and renamed the `lookup()` function to `getType()`.
Can you guys please help checking this issue?
Thank you.

**Comment by dougwilson** [comment] 2021-04-09 18:00
Duplicate of #200

**Closed by dougwilson** 2021-04-09 18:00 UTC
