### ISSUE TITLE
Wrong behavior when handling discontinuous ranges.

### ISSUE THREAD

**Issue by daveying** [pillarjs/send#165] opened 2018-08-09 06:21 UTC
I use `serve-static` middleware with `expressjs` to serve a big file, when I request discontinuous partial content of that big file, `serve-static` will response with the whole file and the status code is 200 rather than 206.
**I later realized that `serve-static` actually use `send` to handle the file reading, and problem happened here.**

e.g. content of my big file (`localhost:5052/test.txt`) is:

```
0123456789
```

If I request with:

```
GET /test.txt HTTP/1.1
Host: localhost:5052
Range: bytes=1-3,6-8 // note, discontinuous
Cache-Control: no-cache
```

The response will be the whole file
```
0123456789
```
But if the range is continuous, it works fine.
```
GET /test.txt HTTP/1.1
Host: localhost:5052
Range: bytes=1-5,6-8 // note, continuous ranges
Cache-Control: no-cache
```
and the response will be:
```
12345678
```

Please fix the bug. Thanks

**Comment by dougwilson** [comment] 2018-08-09 11:49
This is not a bug as this is valid per spec. If you would like support for this, please volunteer to put together a pull request with an implementation:+1:

**Comment by daveying** [comment] 2018-08-09 15:59
I am definitely willing to do that smile , but I noticed @jcready already have some work done on this issue.

**Comment by dougwilson** [comment] 2018-08-21 12:33
Closing issue, then :+1:

**Closed by dougwilson** 2018-08-21 12:33 UTC
