### ISSUE TITLE
Update to newer mime package to support wasm

### ISSUE THREAD

**Issue by alshamma** [pillarjs/send#173] opened 2018-10-16 22:39 UTC
With the current version of send, WebAssembly wasm is returned with a `Content-Type: application/octet-stream` instead of `application/wasm`. This is because send is using mime@1.4.1. An entry for application/wasm exists in mime@1.6.0.

**Comment by dougwilson** [comment] 2018-10-16 22:40
Duplicate of #154

**Closed by dougwilson** 2018-10-16 22:40 UTC
Labels: duplicate
