### ISSUE TITLE
statusCode causing "Error: Can't set headers after they are sent."?

### ISSUE THREAD

**Issue by basickarl** [pillarjs/send#118] opened 2016-10-08 18:46 UTC
This isn't exactly a bug, however I'm attempting to fix a koa module which will work with send. According to this issue: https://github.com/koajs/koa/issues/705 TJ states that the default response status code is set to 404 (unless it's changed I'm guessing). When using the send module I pass the default nodejs request and response objects ctx.req and ctx.res (you can read here http://koajs.com/ a bit down, I pass the original nodejs objects).

Now, since koa sets 404 as default, I'm guessing this is causing the error displayed below:

```
{ Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/send/index.js:326:13)
    at SendStream.send (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/send/index.js:525:17)
    at onstat (/home/karl/dev/node/sketch/experiment/koa-babel-lasso/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:117:15) expose: false, statusCode: 500, status: 500 }
```

I'm wondering, am I correct that this is the issue? I tried setting the response status to 200 (before using send) without any luck (same error).

Any other pointers or advice would be great!

**Comment by dougwilson** [comment] 2016-10-08 18:58
I have personally never used Koa, so not sure. Can you provide a complete test case I can run that reproduces the issue? Then I could attach a debugger and see what the issue is to fix (or you could do that and issue a PR).

**Comment by basickarl** [comment] 2016-10-08 18:59
I'll do so and get back!

**Comment by basickarl** [comment] 2016-10-09 21:43
Ok here ya go:

git clone https://github.com/basickarl/koa-babel-lasso
npm install

After that you must copy the two files in the `koa-babel-lasso/src/lasso_replace` directory (`index.js` and `serveStatic.js`) and paste them (overwriting the original ones) over at `koa-babel-lasso/node_modules/lasso/middleware/koa`. This is the area of the lasso module I'm trying to get to work with send (specifically for koa).

npm run dev
goto 127.0.0.1:3000

**Comment by dougwilson** [comment] 2016-10-09 22:23
Koa is sending a response as soon as your main function returns. Basically, Koa is responding before the file stat returns in send, so send can no longer even respond. I assume this is some kind of Koa behavior, but I don't know enough about Koa to provide a suggestion.

I'm going to defer to you to issue a PR yo fix the issue, as I just don't know enough about how Koa works to know what the right thing to do is.

**Comment by dougwilson** [comment] 2016-10-10 03:52
I was trying to browse around to see if anyone was using this module with Koa so I could see an example, but couldn't really find anything. I did see the Koa GitHub organization has https://github.com/koajs/send which, looking at the source code, looks like basically a port of this module to Koa. So perhaps it's not possible to use this module with Koa? I'm not sure. This module doesn't actually require any specific framework, only requires the raw Node.js HTTP req/res objects. I don't see why you couldn't use it with Koa, but without understanding better how the Koa middleware stack works, I'm not sure how to get it to not send the response after the top-level function returns.

**Comment by dougwilson** [comment] 2016-10-10 03:58
FWIW, I did find that setting `ctx.respond = false` works here, but according to http://koajs.com/#context :

> Note that using this is not supported by Koa. This may break intended functionality of Koa middleware and Koa itself. Using this property is considered a hack and is only a convenience to those wishing to use traditional fn(req, res) functions and middleware within Koa.

So not sure if using that is OK or a bad thing, and if it's bad, if there is any other way to do the processing the "correct way" besides just using a different module.

**Comment by dougwilson** [comment] 2016-10-14 02:51
Hi @basickarl did the `ctx.respond = false` work for you? Did you have time to look into a PR for this module?

**Comment by basickarl** [comment] 2016-10-14 08:12
@dougwilson Hi! I'm still investigating, I'm actually starting to look at the Koa code to see what it actually does. I'll get back when I figure out a solution :)

**Comment by dougwilson** [comment] 2016-10-15 04:02
Hi @basickarl while your issue has been open here, another used dropped by asking how to use this module with Koa and then provided the answer in https://github.com/pillarjs/send/issues/119#issuecomment-253715161 Does that work for you?

**Comment by basickarl** [comment] 2016-10-19 03:15
@dougwilson Thanks for the link! It *does* get it to work by uploading files at the cost unfortunately of breaking koa middleware. I'm still looking into this!

**Comment by dougwilson** [comment] 2016-10-19 03:42
Hi @basickarl can you elaborate more on what is breaking? As far as I can tell from that comment, it seems to work with the whole upstream stuff just fine. What is breaking?

**Comment by basickarl** [comment] 2016-10-19 05:31
@dougwilson It works for Koa v1, however there was a few things wrong with it I got it working properly now with v1.

Koa v1:
```
function* (next) {

    var ctx = this;

    var path = ctx.request.path;
    if (!path.startsWith(routePrefix) || (ctx.request.method !== 'GET' && ctx.request.method !== 'HEAD')) {
        return yield next;
    }

    ctx.respond = false;

    var filePath = path.substring(routePrefix.length);

yield new Promise(function (resolve, reject) {
    send(ctx.req, filePath, sendOptions)
        .on('error', function (err) {
            ctx.status = err.statusCode || 500;
            ctx.res.end('Not found: ' + filePath);
            resolve();
        })
        .on('directory', notFound)
        .on('headers', function (req, path, stat) {
            ctx.status = 200;
        })
        .on('end', function () {
            resolve();
        })
        .pipe(ctx.res);
});
```

As you can see above, setting resolve() fixed the issue. If the file was not found it called reject() which then broke koa, by calling resolve() koa is allowed to countinue to function normally. Would be a perfect time to emit error and have a on error listener (as stated in the koa docs).

Koa v2 however is where I get the error:
```server error Error: Can't set headers after they are sent.```
 So this is what I'm trying to figure out :P

**Comment by basickarl** [comment] 2016-10-19 10:30
@dougwilson Finally! I figured it out. I read the send documentation but it didn't say much so I looked through the source code and looked at the stream emit event. Koa handles streams for you so I just passed the ReadableStream to Koas ctx.body varaible (this is how you stream in Koa). So the below code works for both versions of Koa.

```
yield new Promise(function (resolve, reject) {
	send(ctx.req, filePath, sendOptions)
		.on('error', function (err) {
			ctx.status = err.statusCode || 500;
			ctx.body = 'Not found: ' + filePath;
			// reject(err);
			resolve();
		})
		.on('directory', function () {
			ctx.throw(404);
		})
		.on('headers', function (req, path, stat) {
			ctx.status = 200;
		})
		.on('stream', function (stream) {
			ctx.body = stream;
			resolve();
		})
		.on('end', function () {
			resolve();
		})
		.pipe(ctx.res);
});
```

I've got some questions though, does send continue after I pass stream to ctx.body? It doesn't seem to emit the event 'end'. Or is there something I'm missing (I'm hoping that after I pass the stream it ends as Koa handles the streaming).

**Comment by basickarl** [comment] 2016-10-19 10:44
```
SendStream.prototype.stream = function stream(path, options) {
  // TODO: this is all lame, refactor meeee
  var finished = false
  var self = this
  var res = this.res

  // pipe
  var stream = fs.createReadStream(path, options)
  this.emit('stream', stream)
  stream.pipe(res) // <--- this is unnecessary since koa handles the stream?

  // response finished, done with the fd
  onFinished(res, function onfinished() {
    finished = true
    destroy(stream)
  })

  // error handling code-smell
  stream.on('error', function onerror(err) {
    // request already finished
    if (finished) return

    // clean up stream
    finished = true
    destroy(stream)

    // error
    self.onStatError(err)
  })

  // end
  stream.on('end', function onend() {
    self.emit('end')
  })
}
```

**Comment by basickarl** [comment] 2016-10-19 11:39
I've come up with a little hack, to use with koa:

```
var sendOptions = {
	fallthrough: false,
	redirect: false,
	index: false,
	skipStreamPipe: true // <---
};

send(ctx.req, filePath, sendOptions)
//...
.on('stream', function (stream) {
	ctx.body = stream;
	resolve();
})
```

And in the send index.js:

```


SendStream.prototype.stream = function stream(path, options) {
  // TODO: this is all lame, refactor meeee
  var finished = false
  var self = this
  var res = this.res

  // pipe
  var stream = fs.createReadStream(path, options)

  // end
  stream.on('end', function onend() { // <--- will be called even if koa handles the stream
    self.emit('end')
  })

  // error handling code-smell
  stream.on('error', function onerror(err) { // <--- will be called even if koa handles the stream
    // request already finished
    if (finished) return

    // clean up stream
    finished = true
    destroy(stream)

    // error
    self.onStatError(err)
  })

  this.emit('stream', stream)

  if (options.skipStreamPipe) // <--- koa will handle the stream
    return;

  stream.pipe(res) // <--- not needed since koa handles it on it's own

  // response finished, done with the fd
  onFinished(res, function onfinished() { // pretty sure koa cleans up the stream itself
    finished = true
    destroy(stream)
  })
}
```

For people using nodejs/express they don't have to care about the extra option value.

Does this seem reasonable? Is there anything else that I've missed?

**Comment by basickarl** [comment] 2016-10-19 13:22
Pull request: https://github.com/pillarjs/send/pull/120

**Comment by dougwilson** [comment] 2017-01-21 06:09
Closing in favor of the PR.

**Closed by dougwilson** 2017-01-21 06:09 UTC
